yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('create/', views.post_create, name='post_create'),
    path(
        'posts/<int:post_id>/comment/', views.add_comment, name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about'))
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

from .constants import FIRST_SYMBOLS

User = get_user_model()


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст',
        help_text='Текст поста',
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        'Group',
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост',
    )
    image = models.ImageField(
        blank=True,
        upload_to='posts/',
        verbose_name='Изображение',
        help_text='Изображение для публикации'
    )

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:FIRST_SYMBOLS]


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название группы')
    slug = models.SlugField(max_length=40, unique=True, verbose_name='Слаг')
    description = models.TextField(verbose_name='Описание группы')

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(
        'Post',
        related_name='comments',
        on_delete=models.CASCADE,
        verbose_name='Пост',
    )
    author = models.ForeignKey(
        User,
        related_name='comments',
        verbose_name='Автор',
        on_delete=models.CASCADE
    )
    text = models.TextField(
        verbose_name='Комментарий',
        help_text='Комментария для поста'
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата написания'
    )

    class Meta:
        ordering = ('-created', )
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        related_name='follower',
        on_delete=models.CASCADE,
        verbose_name='Подписчик'
    )
    author = models.ForeignKey(
        User,
        related_name='following',
        on_delete=models.CASCADE,
        verbose_name='Автор'
    )

    class Meta:
        verbose_name = "Подписка"
        verbose_name_plural = "Подписки"
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='unique_user_author'
            )
        ]

    def __str__(self):
        return f'{self.user} - {self.author}'

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    """Форма для создания/редактирования поста."""

    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    """Форма для написания комментария к постам."""

    class Meta:
        model = Comment
        fields = ('text', )

yatube/posts/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.decorators import login_required

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User
from .utils import get_pagination


def index(request):
    """Отображает главную страницу с 10 последними созданными постами."""
    posts = Post.objects.select_related('group',).all()
    page_obj = get_pagination(request, posts)
    context = {
        "page_obj": page_obj,
    }

    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    """Отображает все посты выбранной категории в порядке убывания по дате."""
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    page_obj = get_pagination(request, posts)
    context = {
        'group': group,
        "page_obj": page_obj,
    }

    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    """Отображает профиль зарегистрированного пользователя."""
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    page_obj = get_pagination(request, posts)
    context = {
        'author': author,
        'page_obj': page_obj,
    }
    if request.user.is_authenticated:
        following = Follow.objects.filter(
            author=author, user=request.user
        ).exists()
        context['following'] = following

    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    """Отображает выбранный пост."""
    post = get_object_or_404(Post, pk=post_id)
    comments = post.comments.all()
    form = CommentForm()
    context = {
        'post': post,
        'comments': comments,
        'form': form,
    }

    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    """Отображает форму для создания новой записи."""
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        new_post = form.save(commit=False)
        new_post.author = request.user
        new_post.save()

        return redirect('posts:profile', request.user.username)

    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    """Редактирование выбранного поста."""
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:

        return redirect('posts:post_detail', post.pk)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if request.method == 'POST' and form.is_valid():
        form.save()

        return redirect('posts:post_detail', post.pk)

    context = {'form': form,
               'is_edit': True,
               'post': post}

    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    """Написание комметариев к постам."""
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()

    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    """Отображает посты авторов из подписок пользователя."""
    posts = Post.objects.filter(author__following__user=request.user)
    page_obj = get_pagination(request, posts)
    context = {
        'page_obj': page_obj
    }

    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    """Подписка на интересного и забавного автора."""
    author = get_object_or_404(User, username=username)
    if request.user != author and not Follow.objects.filter(
        author=author, user=request.user
    ).exists():
        Follow.objects.create(user=request.user, author=author)

    return redirect('posts:profile', author.username)


@login_required
def profile_unfollow(request, username):
    """Отписка от надоеливого или скучного автора."""
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()

    return redirect('posts:profile', author.username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}

{% load user_filters %}

{% block title %}
  {% if is_edit %}
    Редактирование поста
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}

{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %}
              Редактирование поста
            {% else %}
              Новый пост
            {% endif %}
          </div>
          <div class="card-body">
            {% include 'includes/form_errors.html' %}
            <form method="post" enctype="multipart/form-data" action="
              {% if is_edit %}
                {% url 'posts:post_edit' post.pk %}
              {% else %}
                {% url 'posts:post_create' %}
              {% endif %}">
              {% csrf_token %}
              {% for field in form %}
                {% include 'includes/form_labels.html' %}
              {% endfor %}
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить запись
                  {% else %}
                    Создать запись
                  {% endif %}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load cache %}

{% block title %}
  Посты по подпискам
{% endblock %}

{% block content %}
  {% include 'posts/includes/switcher.html' with follow=True %}
  <div class="container py-5">
    <h1>Посты по подпискам</h1>
    {% for post in page_obj %}
      {% include 'posts/includes/post_card.html' %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  </div>
{% endblock %}
{% include 'posts/includes/paginator.html' %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %}Посты группы {{ group.title }}{% endblock %}

{% block content %}
  <div class="container py-5">
    <h1>{{ group.title }}</h1>
    <p>{{ group.description }}</p>
    {% for post in page_obj %}
      {% include 'posts/includes/post_card.html' %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  </div>
{% endblock %}
{% include 'posts/includes/paginator.html' %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load cache %}

{% block title %}
  Последние обновления на сайте
{% endblock %}

{% block content %}
  {% include 'posts/includes/switcher.html' with index=True %}
  <div class="container py-5">
    <h1>Последние обновления на сайте</h1>
    {% cache 20 'index_page' page_obj.number %}
    {% for post in page_obj %}
      {% include 'posts/includes/post_card.html' %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% endcache %}
  </div>
{% endblock %}
{% include 'posts/includes/paginator.html' %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}Пост {{ post.text|truncatechars:30 }}{% endblock %}

{% block content %}
  <div class="container py-5">
    <div class="row">
      <aside class="col-12 col-md-3">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
          {% if post.group %}
            <li class="list-group-item">
              Группа: {{ post.group.title }}
              <a href="{% url 'posts:group_list' post.group.slug %}">
                <br>Все записи группы
              </a>
            </li>
          {% else %}
            <li class="list-group-item">
              <p>У поста нет группы</p>
            </li>
          {% endif %}
          <li class="list-group-item">
            Автор: {{ post.author.get_full_name }}
          </li>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            Всего постов автора:  <span >{{ post.author.posts.count }}</span>
          </li>
          <li class="list-group-item">
            <a href="{% url 'posts:profile' post.author.username %}">
              все посты пользователя
            </a>
          </li>
        </ul>
      </aside>
      <article class="col-12 col-md-9">
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
        <p>
          {{ post.text|linebreaksbr }}
        </p>
        {% if request.user == post.author %}
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post.pk %}">
            Редактировать запись
          </a>
        {% endif %}
        <hr>
        <p>Комментариев: {{ post.comments.count }}</p>
        {% include 'posts/includes/comment.html' %}
      </article>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}

{% block title %}Профайл пользователя {{ author.get_full_name }}{% endblock %}
{% block content %}
  <div class="container py-5">
    <h1>Все посты пользователя {{ author.get_full_name }} </h1>
    <h3>Всего постов: {{ author.posts.count }} </h3>
    <h4>Подписчиков: {{ author.following.count }}</h4>
    <h4>Подписок: {{ author.follower.count }}</h4>
    {% include 'posts/includes/follow_btn.html' %}
    {% for post in page_obj %}
      {% include 'posts/includes/post_card.html' %}
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
  </div>
{% endblock %}
{% include 'posts/includes/paginator.html' %}